config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations",
                                    omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    patch 'update_password' => 'registrations#update_password'
  end

  root 'static_pages#home'

  resources :books, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  resources :authors, only: :show
  resources :categories, only: :show
  resources :order_items, only: [:create, :destroy]

  resource :cart, only: [:show, :update, :destroy]

  resources :orders, only: [:index, :show]

  resources :checkout, only: [:show, :update] do
    member do
      get :completed
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @books = Book.bestsellers
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.slim
div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="10000"
  ol class="carousel-indicators"
    li data-target="#carousel-example-generic" data-slide-to="0" class="active"
    li data-target="#carousel-example-generic" data-slide-to="1"
    li data-target="#carousel-example-generic" data-slide-to="2"
  div class="carousel-inner"
    - @books.each_with_index do |book, index|
      .item{ class= "#{ "active" if index == 0 }"}
        div class="row"
          div class="title-book"
            div class="col-xs-12"
              p class="title_with_author"
                = truncate(book.title, length: 45)
              p class="title_with_author"
                |
                  by
              p class="title_with_author"
                = link_to author_path(book.author)
                  => book.author.firstname
                  = book.author.lastname
        div class="row image-and-text"
          div class="col-xs-4"
            = link_to book_path(book)
              = image_tag("default.png")

          div class="col-xs-8"
            p class="description-text-home-page"
              = truncate(book.description, length: 750)

        div class="row"
          div class="col-xs-4"

          div class="col-xs-8"
            div class="row price-and-btn"

              div class="col-xs-2 col-price-book-on-home"
                div class="book-price"
                  = number_to_currency(book.price)

              div class="col-xs-4 add-to-cart-btn-home-page"
                = form_tag(order_items_path(book_id: book.id)) do
                  .input-group
                    = number_field_tag(:quantity, 1, min: 1, class: 'form-control input-field-width')
                    .input-group-btn
                      = hidden_field_tag :book, value: book
                      = hidden_field_tag :price, value: book.price
                      = submit_tag "Add to Cart", class: "btn btn-primary"

  <!-- Controls -->
  a.left.carousel-control[href="#carousel-example-generic" role="button" data-slide="prev"]
    span.glyphicon.glyphicon-triangle-left
  a.right.carousel-control[href="#carousel-example-generic" role="button" data-slide="next"]
    span.glyphicon.glyphicon-triangle-right
  <!-- Carousel -->

div class="footer"
  div class="footer-text"
    | Welcome to our amazing Bookstore! Choose anything you wish, we'll ship it anywhere!