config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations",
                                    omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    patch 'update_password' => 'registrations#update_password'
  end

  root 'static_pages#home'

  resources :books, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  resources :authors, only: :show
  resources :categories, only: :show
  resources :order_items, only: [:create, :destroy]

  resource :cart, only: [:show, :update, :destroy]

  resources :orders, only: [:index, :show]

  resources :checkout, only: [:show, :update] do
    member do
      get :completed
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    authorize! :show, Order
  end

  def update
    authorize! :update, Order
    updating_quantity
    updating_coupon
    redirect_to cart_path
  end

  def destroy
    authorize! :destroy, Order
    @order.destroy
    redirect_to books_path
  end

  private

    def updating_quantity
      @order.order_items.update(params[:items].keys, params[:items].values)
    end

    def updating_coupon
      unless params[:order][:coupon_attributes][:name] == ""
        coupon = Coupon.where("name = ?", params[:order][:coupon_attributes][:name])
        coupon = coupon.first
        if coupon.nil?
          flash[:alert] = "Invalid coupon"
        elsif coupon.present?
          @order.update_attributes(coupon_id: coupon.id)
          flash[:notice] = "You have successfully used coupon"
        end
      end
    end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.slim
- if @order.nil? || @order.order_items.empty?
  p class="text-center"
    | There are no items in your shopping cart. Please
    => link_to "go back", root_path
    | and add some items to your cart.
- else
    = form_tag cart_path, method: "patch" do
      table class="table"
        tr
          td class="table-title"
          td class="table-title"
            | BOOK
          td class="table-title"
            | PRICE
          td class="table-title"
            | QTY
          td class="table-title"
            | TOTAL
          td
        - @order.order_items.each do |order_item|
          = fields_for "items[]", order_item do |f|
            tr class="line-in-cart"
              td
                = link_to book_path(order_item.book)
                  = image_tag("default1.png", class: "image-in-cart")
              td
                p class="book-title-in-cart"
                  = order_item.book.title
                p
                  = truncate(order_item.book.description, length: 180)
              td class="book-price-in-cart"
                = number_to_currency order_item.unit_price
              td
                = f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1

              td class="book-price-in-cart"
                = number_to_currency order_item.total_price

              td class= "book-#{order_item.book.id}"
                = link_to order_item, method: :delete
                  = image_tag("cross.png", class: "cross-in-cart")

        table class="table"
          tr
            td class="left-empty-column"
            td class="text-right title-subtotal-price"
              p class="p-title-for-table"
                | SUBTOTAL:
            td class="text-left total-price-column"
              p class="p-book-price-in-cart"
                = number_to_currency @order.total_price

          - if !@order.coupon.nil?
            tr
              td class="left-empty-column"
              td class="text-right title-for-integer"
                p class="p-title-for-table"
                  | DISCOUNT:
              td class="text-left discount-price-column"
                p class="p-book-price-in-cart"
                  = @order.coupon.discount
                  | %

            tr
              td class="left-empty-column"
              td class="text-right title-for-integer"
                - if !@order.coupon.nil?
                  p class="p-title-for-table"
                    | SUBTOTAL WITH DISCOUNT:
                - else
                  p class="p-title-for-table"
                    | SUBTOTAL:
              td class="text-left total-price-with-discount-column"
                p class="p-book-price-in-cart"
                  = number_to_currency @order.total_price_with_discount

        table class="table"
          tr
            td class="buttons-for-cart"
              = link_to 'EMPTY CART', @cart, method: :delete, class: "btn btn-danger"
            td class="buttons-for-cart"
              = link_to 'CONTINUE SHOPPING', {controller: :books, action: :index}, class: "btn btn-primary"
            td class="empty-column"
            td class="buttons-for-cart"
              = form_for @order do |f|
                = f.fields_for :coupon_attributes do |coupon|
                  = coupon.text_field :name, placeholder: 'Add coupon', class: "form-control coupon-field"
            td class="buttons-for-cart"
              = submit_tag "Update", class: "btn btn-primary btn-update-quantity"
            td class="buttons-for-cart"
              = link_to 'CHECKOUT', checkout_path(:address), class: "btn btn-primary"