config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations",
                                    omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    patch 'update_password' => 'registrations#update_password'
  end

  root 'static_pages#home'

  resources :books, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  resources :authors, only: :show
  resources :categories, only: :show
  resources :order_items, only: [:create, :destroy]

  resource :cart, only: [:show, :update, :destroy]

  resources :orders, only: [:index, :show]

  resources :checkout, only: [:show, :update] do
    member do
      get :completed
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, uniqueness: true, presence: true

  has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: [:show]

  load_and_authorize_resource

  def show
    @categories = Category.all
    @books = @category.books.page(params[:page]).per(9)
  end

  private

    def load_category
      @category = Category.find(params[:id])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.slim
div class="row"
  div class="col-xs-9"
    div class="title-book"
      p class="title-links"
        = link_to 'Home', root_path
        |  >> 
        = link_to 'Shop', books_path
        |  >> 
        = link_to category_path(@category)
            = @category.title
      div
        h2
          | Categories - 
          = @category.title

    div class="col-xs-12"
      div class="row row-eq-height-xs"
        - @books.each do |book|
          div class="col-sm-4 col-lg-4 col-md-4"
            = link_to book_path(book)
              = image_tag("default1.png")
            div class='caption'
              div class="link-button"
                = link_to truncate(book.title, length: 45), book_path(book)
              div class="price-product"
                = number_to_currency(book.price)
      div class="pagination-for-products"
        = paginate @books

  div class="col-xs-3"
    div class="shop"
      h5 class="text-muted"
        | SHOP BY CATEGORIES
      div class="row"
        - @categories.each do |category|
          div class="col-xs-12"
            div class="category"
              = link_to category_path(category)
                = category.title